# Generated by Django 3.1.4 on 2021-02-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210121_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_on',
            new_name='built_on',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.IntegerField(choices=[(1, 'Ebook'), (2, 'Audiobook'), (0, 'Print')], default=0),
        ),
    ]
