# Generated by Django 3.1.4 on 2021-02-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210215_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.IntegerField(choices=[(2, 'Audiobook'), (1, 'Ebook'), (0, 'Print')], default=0),
        ),
    ]
