# Generated by Django 3.1.4 on 2021-02-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210215_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='read_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
