# Generated by Django 3.1.4 on 2021-01-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesApi', '0002_auto_20210101_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
